# Generated by Django 2.2.24 on 2021-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_cover',
            field=models.CharField(default=11, max_length=800),
            preserve_default=False,
        ),
    ]
